removed one email for test
GSA/digitalgov.gov pull request #4654
Opened 2022-03-01 20:38 UTC by aalikaram

This PR implements the following **changes:**

* insert your summary of your request here, add more bullets as needed

**URL / Link to page**

2022-03-02 14:16 UTC, mejiaj commented on content/authors/lt-col-theodore-j-erickson/_index.md
> -email: theodore.erickson@us.af.mil
The spreadsheet lists this as `Federal` [here](https://docs.google.com/spreadsheets/d/1NCE1GqifPoY6t-xZDej8MPESW010lie4gTQGzLk8K6I/edit#gid=0)

2022-03-02 14:17 UTC, mejiaj commented on content/authors/courtney-greenley/_index.md
> -email: "Courtney.L.Greenley@usace.army.mil"
Federal.

2022-03-02 14:17 UTC, mejiaj commented on content/authors/albinko-hasic/_index.md
> -email: Albinko.Hasic@usace.army.mil
Federal.

2022-03-02 14:19 UTC, mejiaj requested changes
Ali, please check the [ticket](https://trello.com/c/dnFbdTXt/592-clean-authors-data#comment-62150b2a9faf053e75e275e5) we're only supposed to remove non-federal emails.

2022-03-07 13:59 UTC, mejiaj approved these changes
LGTM, thanks Ali!

2022-03-08 17:33 UTC, ToniBonittoGSA approved these changes

2022-03-08 17:33 UTC, merged