updated mailto links to display digitalgov@gsa.gov in link copy
GSA/digitalgov.gov pull request #4897
Opened 2022-05-17 13:53 UTC by nick-mon1

This PR implements the following **changes:**

Updated all events pages to display "digitalgov@gsa.gov" in the link text for users to copy. 
This changes "send us an email >>" to include the email address.

Source: [Investigate error on link for "Send us an email »"](https://trello.com/c/ZYmctzCZ)

<img width="713" alt="Screen Shot 2022-05-17 at 9 35 06 AM" src="https://user-images.githubusercontent.com/104778659/168827308-aa8733af-9440-4906-8a5d-801f330abab7.png">

2022-05-17 18:09 UTC, afeijoo commented
LGTM

2022-05-17 20:30 UTC, mejiaj commented on themes/digital.gov/layouts/partials/core/page-data.html
> +  <p class="feedback-copy"><i class="fas fa-question-circle"></i> {{ if .prompt -}}{{- .prompt -}}{{- else -}}Have feedback or questions?{{- end }} <a target="new" href="mailto:{{- if .email -}}{{- .
Can we add some formatting to make this more readable?

Also, I don't think we need all of the `&nbsp;` in the link text.

2022-05-17 20:32 UTC, mejiaj requested changes
Looks good, the email is much clearer.

Just a suggestion on formatting, adding indents and removing the non-breaking spaces from the link text.

2022-05-18 14:35 UTC, nick-mon1 commented
Extracted the lengthy mailto url into variables for easier readability.

2022-05-18 15:50 UTC, mejiaj requested changes
The new formatting looks good, but needs another pass. The email is now showing up blank in outlook.

**Before**
![image](https://user-images.githubusercontent.com/3385219/169086136-86408bb0-2b5d-4913-9659-b79a87082a8f.png)

**After**
![image](https://user-images.githubusercontent.com/3385219/169085959-241b8a54-e48b-4858-be76-0f5d9152a262.png)

```diff
{{/*  Old value  */}}
-<a target="new" href="mailto:digitalgov@gsa.gov?subject=Feedback%3A%20How%20to%20Build%20Your%20Digital%20Dream%20Team&amp;body=%0D%0A---enter%20your%20feedback%2Fquestions%20here---%0D%0A%0D%0A%0D%0A-%20-%20-%20-%20-%20%0D%0APage%3A%20How%20to%20Build%20Your%20Digital%20Dream%20Team%0D%0AURL%3A%20https%3A%2F%2Fwww.digital.gov%2f%2flocalhost%3a1313%2fevent%2f2022%2f05%2f17%2fhow-to-build-your-digital-dream-team%2f%0D%0A-%20-%20-%20-%20-%0D%0A%0D%0A%0D%0AWe%20value%20your%20feedback%20and%20open%20questions.%20Thank%20you%20for%20helping%20to%20make%20our%20pages%20better.%0D%0A%0D%0Ahttps%3A%2F%2Fwww.digital.gov%0D%0A%40digital_gov%20on%20Twitter&amp;cc=digitalgovu%40gsa.gov">Send&nbsp;us&nbsp;an&nbsp;email&nbsp;at&nbsp;digitalgov@gsa.gov</a>

{{/*  New value  */}}
+<a target="new" href="mailto:digitalgov@gsa.gov?subject=Feedback%3A%20How%20to%20Build%20Your%20Digital%20Dream%20Team&amp;amp;body=%0D%0A---enter%20your%20feedback%2Fquestions%20here---%0D%0A%0D%0A%0D%0A-%20-%20-%20-%20-%20%0D%0APage%3A%20How%20to%20Build%20Your%20Digital%20Dream%20Team%0D%0AURL%3A%20https%3A%2F%2Fwww.digital.gov//localhost:1313/event/2022/05/17/how-to-build-your-digital-dream-team/%0D%0A-%20-%20-%20-%20-%0D%0A%0D%0A%0D%0AWe%20value%20your%20feedback%20and%20open%20questions.%20Thank%20you%20for%20helping%20to%20make%20our%20pages%20better.%0D%0A%0D%0Ahttps%3A%2F%2Fwww.digital.gov%0D%0A%40digital_gov%20on%20Twitter&amp;cc=digitalgovu@gsa.gov">
  Send us an email at digitalgov@gsa.gov
</a>
```

2022-05-18 19:55 UTC, nick-mon1 commented
Previous commit was not properly escaping URL encoded characters inside string variables and causing the email details to not be displayed, tested on mac mail and outlook with the new formatting.

<img width="833" alt="Screen Shot 2022-05-18 at 3 50 43 PM" src="https://user-images.githubusercontent.com/104778659/169144785-92f830b8-9bc4-4110-b79d-703af2cef8a4.png">
<img width="781" alt="Screen Shot 2022-05-18 at 3 51 15 PM" src="https://user-images.githubusercontent.com/104778659/169144787-ead18cef-7223-4f70-9d54-7c995d06df72.png">

2022-05-18 20:11 UTC, mejiaj approved these changes
Looks good, thank you!

2022-05-19 13:10 UTC, merged