Audit sites for our short URLs that use go.usa.gov
GSA/digitalgov.gov pull request #5310
Opened 2022-08-31 16:20 UTC by nick-mon1

This PR implements the following **changes:**

* insert your summary of your request here, add more bullets as needed

**URL / Link to page**

2022-09-01 21:01 UTC, mejiaj requested changes
Overall looks pretty good. There are some files that have extra lines and added some comments on other findings.

2022-09-02 17:19 UTC, nick-mon1 commented on content/news/2013/12/2013-12-20-gov-url-shorteners-and-how-to-use-them.md
> +This video explains <a href="http://www.youtube.com/watch?v=QMkltd6dZzU">how Google treats short URLs</a>. For more on 301 redirects, read these tips from <a href="http://www.bing.com/blogs/site_blog
I've updated the link to the new working URL

2022-09-02 17:21 UTC, nick-mon1 commented on content/events/2020/06/2020-06-30-10x-project-lightning-talks-2020.md
>   - Mike Stern, Government Notification Services
Good catch, this is now fixed

2022-09-02 17:26 UTC, nick-mon1 commented on content/news/2020/04/2020-04-24-experimenting-with-micropurchase-threshold.md
> +
Extra space has been removed

2022-09-02 17:29 UTC, nick-mon1 commented on content/news/2020/05/2020-05-20-tapping-into-seo-how-government-websites.md
> +
This is now removed

2022-09-02 17:30 UTC, nick-mon1 commented on content/news/2020/05/2020-05-27-federal-source-code-study-series.md
> +
This is now removed

2022-09-02 17:47 UTC, nick-mon1 commented on themes/digital.gov/src/js/common/clicks.js
> -});
Removed `_clicks.scss` as well as removed the comment section in `baseof.html`. Yes, we will be getting rid of this tracking info for the usa.go.gov sunsetting.

2022-09-02 17:50 UTC, nick-mon1 commented on content/news/2015/09/2015-09-28-nasa-lunar-eclipse-a-supermoon-match-made-in-metrics-heaven.md
> -short_url:
I have removed this, @ToniBonittoGSA should it stay?

2022-09-02 18:42 UTC, mejiaj requested changes
Minor note on some additional click styles, otherwise LGTM!

2022-09-02 18:42 UTC, mejiaj commented on themes/digital.gov/src/scss/new/styles.scss
> -@forward 'clicks';
We can remove click styles on cards too

https://github.com/GSA/digitalgov.gov/blob/23a07f637260ca0c1167bc83bddaa06eddba67ff/themes/digital.gov/src/scss/new/_card.scss#L75-L89

2022-09-02 18:52 UTC, mejiaj commented on themes/digital.gov/src/scss/new/styles.scss
> -@forward 'clicks';
Removed in [65e10a8](https://github.com/GSA/digitalgov.gov/pull/5310/commits/65e10a80365b58d02d65fce754210bc71b46f4d0)

2022-09-02 18:53 UTC, mejiaj commented on themes/digital.gov/src/js/common/clicks.js
> -});
Removed in [23a07f6](https://github.com/GSA/digitalgov.gov/pull/5310/commits/23a07f637260ca0c1167bc83bddaa06eddba67ff)

2022-09-02 19:13 UTC, mejiaj approved these changes
LGTM, thanks Nick!

2022-09-02 19:25 UTC, merged