Add headings to all News items
GSA/digitalgov.gov pull request #5417
Opened 2022-09-28 19:20 UTC by nick-mon1

This PR implements the following **changes:**

* insert your summary of your request here, add more bullets as needed

**URL / Link to page**

2022-09-29 14:10 UTC, mejiaj requested changes
Still getting an error with AXE Devtools

Tested [news preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/nl-add-headings-to-short-links/news/)

![image](https://user-images.githubusercontent.com/3385219/193053275-003a5fe3-3cb6-4a23-b9f6-bb8738ba377d.png)

Seems to be coming from a Hubspot form. The selector is `#newsletter-signup .usa-sign-up .hbspt-form div` and it has an H2 inside.

![image](https://user-images.githubusercontent.com/3385219/193053633-abe1925d-d391-46fb-a4ee-1ddbd27c6532.png)

### We could try

- Changing `usa-sign-up` to a section or article 
- Changing the hubspot form header (or remove all together)
- Set the `.deck` under H1 as an H2 
![image](https://user-images.githubusercontent.com/3385219/193054348-22e0e638-725e-4386-b774-4b75b029576d.png)

2022-09-30 19:52 UTC, nick-mon1 commented
@mejiaj Thanks for the extra catches regarding the deck. I've made the first and last suggestions. The hub spot form will be removed when we replace with GovDelivery. But until then, should I just hide it with CSS?

2022-10-03 14:03 UTC, mejiaj commented
@nick-mon1 it's already hidden via `display: none;`. We'd have to try the suggestions above, mark this as blocked until hubspot is replaced, or find another way.

https://github.com/GSA/digitalgov.gov/blob/8c606573a74eb17307a24beb53e9f3c3e803b4f4/themes/digital.gov/src/scss/new/_newsletter-signup.scss#L29-L35

2022-10-03 17:14 UTC, ToniBonittoGSA approved these changes

2022-10-03 17:14 UTC, merged