Add CSS to ensure alt text is visible when images are turned off
GSA/digitalgov.gov pull request #5625
Opened 2022-11-29 16:34 UTC by nick-mon1

This PR implements the following **changes:**

* insert your summary of your request here, add more bullets as needed

**URL / Link to page**

2022-11-30 15:22 UTC, mejiaj reviewed
@nick-mon1 you could create a partial called `_uswds-overrides.scss` and list it there. 

Additionally, the section seems to already have the color set, if you do something like `color: inherit` on the image will it also be white?

2022-11-30 20:06 UTC, nick-mon1 commented
I moved the code into `_uswds-overrides.scss`.  `color: inherit` does not override the `a:visited` styles so I've kept the same css code, just different location.

2022-12-01 14:49 UTC, ToniBonittoGSA commented
Hi @nick-mon1 
When I turned images off in Chrome, I got

**1 - needs space between domain and 'Logo'**

<img width="420" alt="Screen Shot 2022-12-01 at 9 32 12 AM" src="https://user-images.githubusercontent.com/19961574/205080046-1bd96761-c1a7-4e1d-82e9-fb3d9d3fc9b2.png">


**2 - there's not much room.. what do you recommend for the author icons, like at Dan, Austin, & Joshua's names?**

<img width="538" alt="Screen Shot 2022-12-01 at 9 34 07 AM" src="https://user-images.githubusercontent.com/19961574/205080042-9643e2d7-1a0a-469e-a98e-1bf020936531.png">

and

<img width="1038" alt="Screen Shot 2022-12-01 at 9 39 16 AM" src="https://user-images.githubusercontent.com/19961574/205081111-be6b45ae-dc87-4540-9872-5e9fcbd28a73.png">

**3 - Can the size of the font be different?** 
 - the Search box alt gets cut off
 - In the Jargon Madness article above, it would be great to have a visual cue to show that that the alt text is not a paragraph in the article.

<img width="1028" alt="Screen Shot 2022-12-01 at 9 40 57 AM" src="https://user-images.githubusercontent.com/19961574/205082269-76358699-5714-4dd8-9b1a-11a13af59232.png">

2022-12-02 14:52 UTC, nick-mon1 commented
@ToniBonittoGSA,

1. Space is added in the top logo alt text
2. Author images are decorative and have no alt text, this is fine
3. I've set the text for inline images in the text to display as italicized text

2022-12-02 15:15 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_images.scss
> +p img[alt] {
Let's add this as a more global style.

```suggestion
img[alt] {
```

2022-12-02 15:16 UTC, mejiaj requested changes
Added suggestion for more global styling of alt text. If we need to style component `alt` we can do that in the component's stylesheet.

2022-12-05 15:05 UTC, mejiaj approved these changes

2022-12-05 19:35 UTC, ToniBonittoGSA commented
Thanks!

https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/nl-a11y-images-alt-text-color/2022/11/07/jargon-madness-a-plain-language-exercise/ 

<img width="1213" alt="Screen Shot 2022-12-05 at 2 33 52 PM" src="https://user-images.githubusercontent.com/19961574/205726874-642a7856-fade-4bec-bc69-54392dc59e3e.png">

2022-12-05 19:35 UTC, merged