Fix formatting in resources
GSA/digitalgov.gov pull request #5680
Opened 2022-12-27 17:44 UTC by mejiaj

After confirming rendering issue, I went ahead and looked at other resources listed on Resources landing page and fixed additional. Closes #5679. 

This PR implements the following **changes:**

- Fix formatting so HTML renders correctly
- Remove `<p>` in government case studies to prevent Hugo from rendering empty links multiple times

**URL / Link to page**

2022-12-27 19:03 UTC, afeijoo requested changes
@mejiaj Look good. Before merging, can you also update `govux@gsa.gov` to `digitalgov@gsa.gov`?

2022-12-27 20:27 UTC, afeijoo approved these changes

2022-12-28 14:48 UTC, afeijoo approved these changes

2022-12-28 15:29 UTC, ToniBonittoGSA approved these changes

2022-12-28 15:29 UTC, merged

2022-12-28 17:33 UTC, daguar commented
Thank you!