Create Resource “introduction-to-design-systems”
GSA/digitalgov.gov pull request #5803
Opened 2023-02-10 19:36 UTC by bonnieAcameron

Automatically generated by Netlify CMS

2023-02-13 17:07 UTC, mejiaj requested changes
@bonnieAcameron looks good overall! I think the `source_url` is breaking the preview, so we can remove that.

I've also added some small formatting changes. I tested for functionality and typos.

2023-02-14 14:37 UTC, mejiaj commented on content/resources/introduction-to-design-systems.md
> +source_url: https://digital.gov/resources/intro-to-design-systems
@bonnieAcameron removing lines `3-4` should do it.

2023-02-15 18:08 UTC, bonnieAcameron commented on content/resources/introduction-to-design-systems.md
> +source_url: https://digital.gov/resources/intro-to-design-systems
added the commit!

2023-02-16 21:30 UTC, mejiaj approved these changes
Looks good, thanks for making those changes @bonnieAcameron.

This is ready for your review @ToniBonittoGSA.

2023-02-16 21:56 UTC, ToniBonittoGSA approved these changes

2023-02-16 22:09 UTC, merged