Refactor card event component
GSA/digitalgov.gov pull request #6021
Opened 2023-03-28 16:57 UTC by nick-mon1

- refactored styles, wip on bem
- bemified styles and markup
- added conditional logic for future-past events
- moved markup to one template
- updated templates
- updated test events

## Summary

Basic description of work done. Closes [#issue_no] or [trello_card_title].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-03-29 20:09 UTC, mejiaj requested changes
@nick-mon1 the variant (`card-event-promo`) in this case should have minimal overrides. Is it possible to reduce them? I see some duplicate styles in children, like card event date.

2023-03-29 20:09 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_card-event.scss
>  }
Are all of these styles necessary for past events? Does that mean future events is the default state?

2023-03-29 20:09 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_card-event.scss
> +  @include u-border-top(0);
Consider keepting the border, but making the color transparent to avoid a shift in layout.

2023-03-29 20:09 UTC, mejiaj commented on themes/digital.gov/layouts/events/card-event.html
> +<article class="card card-event {{ if $eventDate }}card-event-promo{{ else }}card-event-past{{ end }} card-linked" data-edit-this="{{- $path -}}" {{ if .Params.short_url }}data-short_url="{{- .Params
Consider using `card-event--promo` for the class.

2023-04-05 16:29 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_card-event.scss
> +  @include u-border-top(0);
I've removed border in [f4ece54](https://github.com/GSA/digitalgov.gov/pull/6021/commits/f4ece543373aec364248d25f530ae7aab85ff118).

2023-04-05 16:30 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_card-event.scss
>  }
Duplicate and unused styles removed in [f4ece54](https://github.com/GSA/digitalgov.gov/pull/6021/commits/f4ece543373aec364248d25f530ae7aab85ff118).

2023-04-05 16:56 UTC, mejiaj requested changes
@nick-mon1 looks good overall, but could you please take a look at a few things?

1. The [event logic](https://github.com/GSA/digitalgov.gov/blob/99535f5a087a887e9b9d9a277478bfdf6c725c09/themes/digital.gov/layouts/news/list.html#L54-L60) in news landing. Looks like it could be simplified.
2. Events are no longer sorted from new to old on the homepage.
    ![image](https://user-images.githubusercontent.com/3385219/230150569-6286c769-770a-4797-9ccb-882e4fd48867.png)
3. Any visual regressions in the new event card. I've done some formatting updates and removed some unused/duplicate styles.

2023-04-07 19:46 UTC, mejiaj approved these changes

2023-04-20 17:08 UTC, ToniBonittoGSA approved these changes
w00t!

2023-04-20 17:08 UTC, merged