Refactor breadcrumb component to USWDS
GSA/digitalgov.gov pull request #6057
Opened 2023-04-20 19:32 UTC by nick-mon1

## Summary

Update Digital.gov breadcrumb to use [USWDS breadcrumb](https://designsystem.digital.gov/components/breadcrumb/) component.
There are two variants of the breadcrumb
- a single level `breadcrumb` used on content pages
- a multi-level `breadcrumb` used on guides pages

**Content Page**

Single level  back button ("All Resources" purple text with icon)

![[backcrumb.png]]
**Guides Page**

Custom breadcrumbs component

![[breadcrumb-dg.png]]

### Preview

[Link to Preview]()

### Solution

1. Implement `uswds breadcrumb` component
2. Truncate title to first 50 characters for current page position
3. All third level content pages should display breadcrumb

### How To Test

1. Content page - [](2023/03/24/who-is-your-website-manager/)
2. Guides page - [](2018/04/02/marketing-government-through-agency-partnerships/)

#### Pages Affected

| pages                              |
| ----------------------- |
| default/images.html      |
| default/list.html        | 
| default/single.html     |
| communities/single.html |
| events/single.html      |
| guides/list.html        |
| guides/single.html      |
| news/single.html        |
| resources/single.html   |
| services/single.html    |
| topics/list.html        |

### Screenshots

**Content Page**
![[breadcrumb-page.png]]

**Mobile**

![[breadcrumb-mobile.png]]

**Truncated Page Name**

![[breadcrumb-truncate.png]]

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-04-27 18:15 UTC, mejiaj requested changes
Great job, just a minor comment!

2023-04-27 18:15 UTC, mejiaj commented on themes/digital.gov/src/scss/new/guides/_guide-header.scss
> +    // @include u-border-top(0, !important);
Can we remove this code?

2023-05-01 16:25 UTC, nick-mon1 commented on themes/digital.gov/src/scss/new/guides/_guide-header.scss
> +    // @include u-border-top(0, !important);
Code is now removed!

2023-05-03 17:46 UTC, mejiaj approved these changes

2023-05-04 17:53 UTC, merged