Added formatting & linting for styles
GSA/digitalgov.gov pull request #6120
Opened 2023-05-10 19:57 UTC by nick-mon1

## Summary

Adds style linting and formatting for **scss** files.
Implements [18F TTS CSS Coding Standards](https://www.npmjs.com/package/@18f/identity-stylelint-config) for linting.
Related to https://github.com/GSA/digitalgov.gov/pull/6045.

- testing and fixing style formatting issues
- lint css styles
- adds format and lint checks to CircleCI
- fix SASS errors

### Preview

[Link to Preview]()

### Solution

1. Ran prettier check to view errors: `npx prettier -c ./themes/**/*.scss`
2. Ran prettier write to fix templates: `npx prettier -w ./themes/**/*.scss`
3. Ran stylelint to view and fix style errors: `stylelint ./themes/**/*.scss --fix`

 
### How To Test

1. Run npm scripts
2. CircleCI job runs new style formatting — [CircleCI Logs](https://app.circleci.com/pipelines/github/GSA/digitalgov.gov/14137/workflows/6da3354d-8a4c-41e5-805d-6fdf87c758e2/jobs/35466)

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-05-11 18:16 UTC, mejiaj commented on .stylelintrc.json
> +    "no-duplicate-selectors": null
Let's test and confirm that we want to keep these rules.

2023-05-11 18:38 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_authors-list-short.scss
> +    z-index: 2;
Let's move z-index next to other original styling rules, before breakpoint mixin.

```suggestion
    @include u-font("sans", "2xs");
    z-index: 2;

    @include at-media("tablet") {
      @include u-font("sans", "2xs");
    }
```

2023-05-11 18:45 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_buttons.scss
> +
```suggestion
  @include u-bg("indigo-60v");
  transition: background-color 0.2s, border 0.2s, border-color 0.2s;


  @include at-media("tablet") {
    @include u-padding-y("105");
    @include u-padding-x(3);
    @include u-font("sans", "md");
  }

  i {
    @include u-margin-left("05");
  }


```

2023-05-11 18:48 UTC, mejiaj requested changes
Looking good, added comments to improve clarity.

2023-05-17 16:17 UTC, nick-mon1 commented on themes/digital.gov/layouts/_default/baseof.html
See the github edit button

2023-05-17 16:19 UTC, nick-mon1 commented on themes/digital.gov/layouts/home.html
See top of homepage "Popular guides and resources"

2023-05-17 17:18 UTC, nick-mon1 commented on themes/digital.gov/layouts/services/service-contact.html
[Preview link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-style-formatting-patch-1/services/directory/)

<img width="260" alt="Screen Shot 2023-05-17 at 1 17 54 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/e6784b58-7aa7-4e5f-8b67-f28cad4e8e19">

2023-05-17 17:19 UTC, nick-mon1 commented on themes/digital.gov/src/js/common/edit-this.js
See the github edit button in the right bottom corner.

2023-05-17 17:21 UTC, nick-mon1 commented on themes/digital.gov/src/js/common/github.js
Added `editFile`, see the github edit button in the right bottom corner.

2023-05-18 15:49 UTC, mejiaj requested changes
Overall looks good, added some notes for minor things.

2023-05-18 15:49 UTC, mejiaj commented on .circleci/config.yml
Can we update these tasks to run tests without fixing?

These CI tasks should check for linting & formatting, but **not** fix them. Those fixes should be made in code so we can save those fixes in git history. These checks should be for code quality and fail if we're not meeting it.

Markdown is an exception, for now, because we don't want workflow builds to fail.

2023-05-18 15:49 UTC, mejiaj commented on package.json
> +    "lint:styles": "npx stylelint ./themes/**/*.scss --fix",
Let's separate linting and fixing tasks.

```suggestion
    "lint:styles": "npx stylelint ./themes/**/*.scss",
    "lint:styles:fix": "npx stylelint ./themes/**/*.scss --fix",
```

2023-05-18 15:49 UTC, mejiaj commented on package.json
> +    "test:templates": "npx prettier -c ./themes/**/*.html",
Same with testing and fixing formatting.

```suggestion
    "prettier:styles": "npx prettier -c ./themes/**/*.scss",
    "prettier:styles:fix": "npx prettier -w ./themes/**/*.scss",
    "prettier:templates": "npx prettier -c ./themes/**/*.html", 
    "prettier:templates:fix": "npx prettier -w ./themes/**/*.html",
    "test:htmlproofer": "htmlproofer ./public --allow-hash-href --check-html --empty-alt-ignore --disable-external",
    "test:pa11y": "npx pa11y-ci --config .pa11yci",
```

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_list-topics.scss
> +    @include u-position("relative");
This position mixin should be above CSS rules.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_news.scss
> +      @include u-bg("blue-warm-5");
This bg mixi should be alongside padding.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_promos.scss
> +  @include u-flex("justify");
Can we move these to the top where they belong? Keeping them here makes it hard to tell what exactly it's styling.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_uswds-theme.scss
> +  /*Colors from _uswds_theme-color.scss*/ $theme-color-base-lightest:
Let's return to the SCSS comment.
```suggestion
  // Colors from _uswds_theme-color.scss
  $theme-color-base-lightest:
```

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_video.scss
> +
No space necessary between includes and native properties.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_video.scss
> +
Again, no space necessary here.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_video.scss
> +
Extra blank line.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_video.scss
> +
Extra blank line.

2023-05-18 15:49 UTC, mejiaj commented on themes/digital.gov/src/scss/new/_video.scss
> +    @include u-height("auto");
Includes should come first, before css properties.

2023-05-18 17:56 UTC, nick-mon1 commented on themes/digital.gov/src/scss/new/_uswds-overrides.scss
> +}
Nope, removed.

2023-05-22 14:30 UTC, mejiaj approved these changes
Looks good, I tested:

- [x] Verified new CI tasks
- [x] CI tasks are passing
- [x] Styles have been linted and formatted

2023-05-22 21:42 UTC, ToniBonittoGSA approved these changes

2023-05-22 21:42 UTC, merged