Create Call to Action Buttons on Home Page
GSA/digitalgov.gov pull request #6317
Opened 2023-07-14 22:10 UTC by jacksonmoody

## Summary

Created call to action buttons highlighting events and communities on the digital.gov home page. 

### Preview

[Link to Preview]()

### Solution

#### Before

#### After

### How To Test

1. Visit the home page
2. Verify that both call to action buttons function correctly

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-07-18 15:18 UTC, jacksonmoody commented on themes/digital.gov/src/scss/new/_buttons.scss
Thanks! Addressed in [b81d024](https://github.com/GSA/digitalgov.gov/pull/6317/commits/b81d02472ea354f86d420373299bc4892478bcea)

2023-07-18 18:40 UTC, nick-mon1 requested changes
@jacksonmoody I pushed some style changes for the new buttons to remove the extra spacing mostly for mobile. I also refactored the `margin`, `padding`, and `color` to use uswds tokens. Take a look and feel free to accept or modify.

2023-07-18 19:56 UTC, jacksonmoody commented
> @jacksonmoody I pushed some style changes for the new buttons to remove the extra spacing mostly for mobile. I also refactored the `margin`, `padding`, and `color` to use uswds tokens. Take a look and feel free to accept or modify.

LGTM, thanks! I just modified to use more native properties, but otherwise should be ready :)

2023-07-20 20:13 UTC, mejiaj approved these changes
Looks good on both small and large screen sizes.

2023-07-24 21:31 UTC, ToniBonittoGSA approved these changes
Nice!

2023-07-24 21:31 UTC, merged