HCD #2: Add Glossary Component
GSA/digitalgov.gov pull request #6420
Opened 2023-08-04 21:43 UTC by jacksonmoody

## Summary

Adds the [18F Glossary Component](https://github.com/18F/glossary) to all HCD guide pages. 
> [!WARNING]  
> Requires #6419 to be merged first

### Preview

[Link to Preview]()

### How To Test

> [!NOTE]  
> In future iterations, we should look into ways to have different glossaries on different page types. Will require communication between Hugo and Javascript, and may require moving away from 18F component.

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-08-09 16:02 UTC, nick-mon1 requested changes
>Overall, great work @jacksonmoody! I wonder if we should move the glossary link into the menubar? I think it would handier if a guide is using the glossary to put it an easier to find location than at the top of the page. @mejiaj what do you think?

A few concerns with this approach. I'd hesitate to add a duplicate link and the header spacing is already tight, so this would take the space of a potential guide link.

I see it's already been added, so we can follow-up later to avoid rework.

2023-08-09 16:20 UTC, mejiaj requested changes
Minor suggestions for improving a11y and code style.

2023-08-10 07:37 UTC, jacksonmoody commented
Thanks for the great feedback guys! Ultimately, I ended up refactoring a lot of the source code for the glossary component. This allowed me to address all of the styling changes that you suggested, and to address the concerns about the archived repository (I tried to bring all of the old JS code up to date). 

I also went ahead and modified the code so that every guide can support a different glossary. While this implementation does require passing in a Hugo variable using `<script>` tags, I think it's worth it in terms of increased flexibility for this component going forward!

To test, you can add a new `.json` file under the `themes/digital.gov/static/glossary` directory. Then, go to the `_index.md` file of any guide and add a `glossary` parameter in the front matter with the name of the `.json` file:

`glossary: "hcd-glossary.json"`

This should create a link to a glossary with these new terms on your chosen guide!

2023-08-13 21:10 UTC, mejiaj requested changes
LGTM for the most part. 

Just some concerns on the now duplicate glossary link and some older methods used in the glossary script. If we could modernize it that would greatly help with readability and maintenance.

2023-08-13 21:10 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
> +};
We could use a more modern method like [Element: toggleAttribute() method | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute) or [HTMLDetailsElement | MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event).

2023-08-13 21:10 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
Nice work making the glossary more usable. Just a few concerns:

1. I don't believe we're using prototypes in other scripts. Are there major benefits to using it here?
2. Event listeners are all typically included in the `init()` function. If there are too many, consider grouping them (for example `click` on the parent and then checking if the target or currentTarget matches).
3. There are more modern methods since ES6 to do a lot of these things, like `matches()` for example.
4. Some areas could use another pass for simplification.

2023-08-14 17:35 UTC, jacksonmoody commented on themes/digital.gov/src/js/glossary.js
> +  this.body = document.querySelector(selectors.glossaryID);
Refactored to remove IDs since we're moving towards using classes in the rest of the codebase

2023-08-14 17:39 UTC, jacksonmoody commented on themes/digital.gov/src/js/glossary.js
> +}
Nice! This is a bit of legacy code from the 18F implementation, but removed seeing as it's so well supported.

2023-08-14 21:41 UTC, nick-mon1 requested changes
@jacksonmoody I've made a commit with a list of changes for smaller functions, improving documentation to functions, and some small style changes and a11y fix. Take a look and we can discuss if need be.

2023-08-15 23:02 UTC, jacksonmoody commented
Thanks for the comments, all! Based on @mejiaj's feedback and discussions with @nick-mon1, I've refactored `glossary.js` by moving away from the prototype structure, breaking up the code into smaller functions, and incorporating more modern ES6 features. I've also incorporated some accessibility improvements—take a look and let me know what you think!

2023-08-16 16:55 UTC, mejiaj requested changes
Almost there. Added final comments, no issues with visual regressions.

Concerns with the lack of semantic markup in glossary and some of the javascript, but we can work on those as a follow-up. I'll create a trello card.

2023-08-16 16:55 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
> +}
Couldn't you combine these?

```suggestion
if (glossaryBody && glossaryPath) {
  initializeGlossary(glossaryPath);
}
```

2023-08-16 16:55 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
> +    if (e.keyCode === KEYCODE_ESC) {
`keyCode` is deprecated, use `.code` instead.

```js
    if (e.code === "Escape") {
```

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

2023-08-16 16:55 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
> +      .forEach((definition) => definition.toggleAttribute("hidden"));
It's generally not recommended to style based on the `hidden` attribute, unless you're using something like `display: none`.

We should instead use an `active` class that will change from the default state.

2023-08-16 16:55 UTC, mejiaj commented on themes/digital.gov/src/js/glossary.js
> +    }
Can we simplify this for clarity? Consider combining.

2023-08-16 17:00 UTC, jacksonmoody commented on themes/digital.gov/layouts/_default/baseof.html
> +    {{- if and ($terms) (os.FileExists (printf "%s/%s" "themes/digital.gov/static/glossary/" $terms)) -}}
The issue is all of this logic is needed to define the glossaryPath which is defined in the script tag. We could move this to the glossary template, but that would require adding another script tag in that file (which seems against the current pattern of keeping all the script tags in one place)

2023-08-16 18:14 UTC, mejiaj commented on themes/digital.gov/layouts/_default/baseof.html
> +    {{- if and ($terms) (os.FileExists (printf "%s/%s" "themes/digital.gov/static/glossary/" $terms)) -}}
We can leave as-is for now, but I'd prefer to move away from the pattern of leaving section-specific JS in _all_ templates.

It makes more sense to modify the code where it lives naturally, in this case Guides. This makes it easier to modify & users aren't downloading unnecessary scripts.

2023-08-16 18:22 UTC, mejiaj approved these changes
Thanks for those changes.

I was able to successfully:
- [x] Add glossary.
- [x] Toggle clicking the button in Guide header.
- [x] Close by clicking the `X` button.
- [x] Close by clicking document body.
- [x] Close by hitting <kbd>Esc</kbd>
- [x] Tab through items.

2023-08-16 19:34 UTC, nick-mon1 approved these changes
Great refactoring work on `glossary.js` @jacksonmoody. I appreciate that!

2023-08-18 17:17 UTC, merged