HCD #4: Refactor Previous/Next Buttons
GSA/digitalgov.gov pull request #6423
Opened 2023-08-04 23:00 UTC by jacksonmoody

## Summary

- Extracts individual buttons into a partial to simplify code logic. 
- Removes support for unnecessary third level of navigation. 
- Added arrow icons and text of previous/next page to improve clarity.

### Preview

[Link to Preview]()

### Solution

### How To Test

Ensure there are no regressions on any of the existing guides pages, and that the buttons function as intended on guides with multiple levels of navigation. (You will need to create a new .yml file in the `guidedata` folder to test this. See `_example.yml` for an example.) 

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-08-15 17:54 UTC, mejiaj requested changes
Love how simple the code looks in comparison. 

Added questions related to example YML and  potential issues with legacy code.

2023-08-15 17:54 UTC, mejiaj commented on data/guidenav/_example.yml
## Questions

1. Is the structure for this still valid? 
2. Can we fix formatting? The indents seem off.
3. Any insights on what `connected-government.yml` and `termsofservice.yml` are for? It seems to show an older YML structure (uses `guidenav` instead of `nav`).

### Validating _example.yml

Pasting in this sample code into `mobile-principles.yml` results in the `prev/next` nav **not** appearing.

**Mobile principles default data**
<img width="844" alt="image" src="https://github.com/GSA/digitalgov.gov/assets/3385219/fe16a272-ed8f-4fb2-84c9-280c1d73b341">

**Using data from `_example.yml`**
<img width="844" alt="image" src="https://github.com/GSA/digitalgov.gov/assets/3385219/6accf2c7-2f27-44c1-ac4c-e42f16fdd12e">


>**Note**
>You can see the `showNextPrevious: true` on line 2.

2023-08-15 23:31 UTC, jacksonmoody commented on data/guidenav/_example.yml
Thanks for the feedback! Honestly, I'm not sold on the necessity of the `_example.yml` file. By design, we don't show the previous/next buttons for pages that don't actually exist. However, this may lead to the unexpected behavior you experienced, where developers copy and paste the `_example.yml` file and expect everything to work (the top menu bar and sidenav won't work either with the `_example.yml` file). 

Moreover, I believe the original purpose of `_example.yml` was to showcase a guide with multiple layers of navigation (as all of the previous guides only had one layer). However, once the `.yml` files for the HCD guides are merged in, this will no longer be an issue.

Because of this, I went ahead and removed `_example.yml` in [aa380f8](https://github.com/GSA/digitalgov.gov/pull/6423/commits/aa380f84995bfe9e69ed4e3e0bfa2e3ce674d369). However, happy to discuss other solutions too!

2023-08-15 23:36 UTC, jacksonmoody commented on data/guidenav/_example.yml
I also fixed the `.yml` formatting in [b4b6402](https://github.com/GSA/digitalgov.gov/pull/6423/commits/b4b6402db850c7ba1e95abde04c8cd0aad6e2764) and removed `connected-government.yml` and `termsofservice.yml`. The only references to these files that I could find were in [this resource](https://github.com/GSA/digitalgov.gov/blob/c17a33e9158b044d3139bb0f8af55d7cba339d32/content/resources/mobile-user-experience-guidelines-and-recommendations.md) and [this resource](https://github.com/GSA/digitalgov.gov/blob/c17a33e9158b044d3139bb0f8af55d7cba339d32/content/resources/federal-compatible-terms-of-service-agreements.md), however, I found no regressions after removing them. (See: [c17a33e](https://github.com/GSA/digitalgov.gov/pull/6423/commits/c17a33e9158b044d3139bb0f8af55d7cba339d32)).

2023-08-16 17:56 UTC, nick-mon1 requested changes
I found no regression errors for `data/guidenav/termsofservice.yml` and `data/guidenav/connected-government.yml`.

2023-08-16 17:56 UTC, nick-mon1 commented on data/guidenav/_example.yml
As for removing `example.yml` my thought was a dev could use as an example for more guides with nested sections of content, but looks like HCD guides will provide that. We should make a note about non-existent links/pages will cause buttons to not display as a comment in one of those `yml` files.

I tested the `dap.yml` with a **subnav** with real pages and the `next/prev` buttons work as expected but the old sidenav doesn't update when using the buttons.

> **NOTE**
>  I've added for regression testing when we merge into the main HCD branch.

```
showNextPrevious: true
showInPageNav: true
nav:
  - title: "Overview"
    path: "/guides/dap/_index.md"
  - title: "Add your site"
    path: "/guides/dap/add-your-site-dap.md"
  - title: "Share DAP data"
    path: "/guides/dap/guidelines-for-sharing-dap-data.md"
    subnav:
      - title: "subnav-testing-page-1"
        path: "/guides/dap/test/test-subnav-page-1.md"
      - title: "subnav-testing-page-2"
        path: "/guides/dap/test/test-subnav-page-2.md"
  - title: "Common questions"
    path: "/guides/dap/common-questions-about-dap.md"
  - title: "Access the data"
    path: "/guides/dap/gaining-access-to-dap-data.md"
```

When I copied the contents from the `_example.yml` with no links to real pages, the `next/prev` buttons do not appear, as you explained.

We could put some notes at the top of `_example.yml` with this callout about non-existent links will cause issues with the display of the `next/prev` buttons.

See this video of my local testing:

https://github.com/GSA/digitalgov.gov/assets/104778659/e5f75a74-7a48-48f3-96e6-ca959c9e207f

2023-08-16 17:56 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/guides/guide-prev-next.html
> +  {{- $pointItem := 0 -}}
We use `$prevItem` and `$prevPage` which makes `$pointerItem` and `$pointerPage` a bit confusing at first. I would suggest updating it to use `$nextItem` and `$nextPage` to improve readability.

2023-08-16 17:56 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/guides/guide-prev-next.html
> +      {{- if not (eq $prevItem 0) -}}
It would help for future reference to add a comment above the `if` block with a short explanation of what it does.

2023-08-16 17:56 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/guides/guide-prev-next.html
>        {{- end -}}
Same thing for line 36 `{{- if $item.subnav -}}`, adding a comment that explains what it does would be helpful.

2023-08-16 17:56 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/guides/guide-prev-next-button.html
Great refactoring for this file. Very simple to understand.

2023-08-16 18:11 UTC, jacksonmoody commented on data/guidenav/_example.yml
Ok sounds good! I'll leave out example.yml for now and then add some clarifying comments to the HCD guide ymls. And as for the old sidenav not working... that's because it's old lol. The new sidenav should work with this same structure.

2023-08-16 19:11 UTC, nick-mon1 approved these changes
Thanks for the code comments and updates!

2023-08-16 20:20 UTC, mejiaj commented on data/guidenav/_example.yml
Removing for now is fine. We can bring back later to document what's expected. There _is_ long term benefit to having an up-to-date and accurage `example.yml` or a README.

2023-08-16 20:22 UTC, mejiaj approved these changes
Thanks for the refactor.

FWIW, I _do_ see benefit to having a README or `_example.yml`, but in this case its better to remove than to have inaccurate / very outdated information.

2023-08-18 17:46 UTC, merged