Create topics-collection landing page
GSA/digitalgov.gov pull request #6604
Opened 2023-09-15 14:11 UTC by nick-mon1

- First refactoring for topics-collection page
- Refactored topics to show standard or collection
- Refactored collection component for topics-collection template
- Setup yaml file and refactored template logic and collection component

## Summary

Basic description of work done. Closes [#issue_no].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-09-21 19:19 UTC, bonnieAcameron requested changes
Looks good, Nick! I added my comments. I have a few design ideas that are small. I will capture them in another comment.

2023-09-21 19:19 UTC, bonnieAcameron commented on content/topics/design/_index.md
> +      name: "21 Century IDEA"
```suggestion
      name: "21st Century Integrated Digital Experience Act (21st Century IDEA)"
```

2023-09-21 19:19 UTC, bonnieAcameron commented on content/topics/design/_index.md
> +        kicker: "HCD Guides"
```suggestion
        kicker: "Human-Centered Design Guide Series"
```

2023-09-21 19:19 UTC, bonnieAcameron commented on content/topics/design/_index.md
> +  top_resources_header: "Essential knowledge for design"
```suggestion
  top_resources_header: "Design: essential knowledge"
```

2023-09-21 19:19 UTC, bonnieAcameron commented on themes/digital.gov/layouts/partials/core/topics/topics-collection.html
> +        <h2>Events for {{ .Title }}</h2>
```suggestion
        <h2>{{ .Title }} events</h2>
```

2023-09-21 19:19 UTC, bonnieAcameron commented on themes/digital.gov/layouts/partials/core/topics/topics-collection.html
> +        <h2>News on {{ .Title -}}</h2>
```suggestion
        <h2>{{ .Title -}} news</h2>
```

2023-09-21 20:12 UTC, bonnieAcameron commented
Design comments:
Overall lovely!

We may want to address: 

- a different style applied to "join the community" than to a "guide". Maybe the dg-ring for "join the community"?
- I think I want the image on the policy card to look a little more "official." example incoming:

2023-09-22 20:23 UTC, bonnieAcameron commented
@nick-mon1 here is the image we chose: 
![legal-judicial-bro-vector-istock-getty-images-1388107868](https://github.com/GSA/digitalgov.gov/assets/96838068/ee8c65e1-9972-41a8-856a-72f9b112088d)

2023-09-25 17:04 UTC, nick-mon1 commented
@bonnieAcameron I like the idea of using something different for the 'communities' block, the `ring` shortcode doesn't take in links. It's more of a glorified text box. We can discuss better ideas for this.

2023-09-25 19:38 UTC, ToniBonittoGSA commented
@nick-mon1 
In the [2nd preview link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-topics-collection-template/topics/agile/), `News and Events on Agile` should be styled the same as `Resources on Agile` and `Join a Community of Practice`. 

Last copy in the Wayback Machine, June 2023: https://web.archive.org/web/20230601145635/https://digital.gov/topics/agile/ 

Thx!

2023-09-27 13:48 UTC, bonnieAcameron submitted a review, later dismissed
Looks great!

2023-09-28 20:58 UTC, mejiaj submitted a review, later dismissed

2023-09-28 23:02 UTC, ToniBonittoGSA submitted a review, later dismissed

2023-09-29 16:03 UTC, merged