Update CX to Customer Experience
GSA/digitalgov.gov pull request #6940
Opened 2023-11-16 14:49 UTC by clmedders

## Summary

This PR will update any reference of `CX` to `Customer Experience` and remove the topic `Customer Expereince Community of Practice

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-11-16 16:14 UTC, bonnieAcameron requested changes
One styling change, then all good!

2023-11-16 16:14 UTC, bonnieAcameron commented on content/topics/customer-experience/_index.md
>  title: "Customer Experience"
```suggestion
title: "Customer experience"
```

2023-11-16 16:14 UTC, bonnieAcameron commented on content/topics/customer-experience/_index.md
>  title: "Customer Experience"
Changing to sentence case (style guide)

2023-11-16 21:37 UTC, bonnieAcameron submitted a review, later dismissed

2023-11-17 14:36 UTC, ToniBonittoGSA commented
@clmedders This accidentally deletes the CX community page; please restore

2023-11-17 20:34 UTC, nick-mon1 commented
### Fixes

1. removed duplicates from front matter due to original `cx` duplicates
2. updated footer link `https://digital.gov/topics/cx/` in 4 pages to `https://digital.gov/topics/customer-experience/`
3. added `communities/customer-experience.md` 

### Notes

Customer experience is written in plain language but the other topics are in Title Case.

@bonnieAcameron Should we keep this title case for consistency?

<img width="1046" alt="Screen Shot 2023-11-17 at 2 22 15 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/7dbfea11-b754-405e-8e45-a3aa4f332fe1">

2023-11-17 20:41 UTC, nick-mon1 requested changes
@clmedders I made some corrections and fixes to help get this closed, hope you don't mind.

### Fixes

1. removed duplicates from front matter due to original `cx` duplicates
2. updated footer link `https://digital.gov/topics/cx/` in 4 pages to `https://digital.gov/topics/customer-experience/`
3. added `communities/customer-experience.md` 

### Notes

Customer experience is written in plain language but the other topics are in Title Case.

@bonnieAcameron Should we keep this title case for consistency?

<img width="1046" alt="Screen Shot 2023-11-17 at 2 22 15 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/7dbfea11-b754-405e-8e45-a3aa4f332fe1">

2023-11-20 21:53 UTC, ToniBonittoGSA approved these changes

2023-11-20 21:54 UTC, merged