Update Better websites. Better government. tagline
GSA/digitalgov.gov pull request #7101
Opened 2023-12-08 14:50 UTC by bonnieAcameron

## Summary
Update home page tagline.

### Preview

- [Homepage Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/bc-update-tagline/)
- [Sources Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/bc-update-tagline/sources/digitalgov/)

**Home Page**
<img width="1533" alt="Screen Shot 2023-12-08 at 10 41 07 AM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/3b7d403d-c130-49cf-9112-62287479cd52">

**Sources**
<img width="1202" alt="Screen Shot 2023-12-08 at 10 46 49 AM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/6a21ab67-c9bc-4a19-a39e-3e0b475c757d">

### Solution

### How To Test

1. Check that I didn't "double" update a source file and the home page. 
2. Check the design on the home page. Does it read well? Do we need to adjust?
---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2023-12-08 15:44 UTC, nick-mon1 commented on config.yml
`dg_tagline` is not used in any template files. We should update `home.html` to set it once.

2023-12-22 15:00 UTC, mejiaj commented on themes/digital.gov/layouts/home.html
> +                {{ $.Site.Params.dg_tagline }}
Used the site variable here for easier updating in the future.

2023-12-22 15:01 UTC, mejiaj submitted a review, later dismissed
Looks good, modified the home template for easier editing in the future.

2023-12-26 15:28 UTC, mejiaj commented on config.yml
No, we should be using it wherever possible to make it easier to update in the future. I used it in 0986de2.

2023-12-26 17:04 UTC, nick-mon1 approved these changes
LGTM, thanks for the code change on using the hugo site params @mejiaj

2023-12-26 17:17 UTC, nick-mon1 requested changes
Found a mobile display issue, but is related to https://github.com/GSA/digitalgov.gov/pull/6872. Creating a bug fix in trello for this.

<img width="406" alt="Screen Shot 2023-12-26 at 12 14 23 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/32d206da-f678-44eb-9eec-975b7dfad5a4">

2023-12-26 17:29 UTC, nick-mon1 approved these changes

2023-12-27 18:21 UTC, merged