Remove Edit Button
GSA/digitalgov.gov pull request #7237
Opened 2024-01-23 20:31 UTC by clmedders

## Summary

This Pr will remove the edit button that lives on the site that allows users the ability to suggest edits via github 

This will also remove the other edit button at the end of the pages along with the `last updated` functionality. 

Will also update the footer link to `Submit issue on GitHub` and link to the issues page for users to make and issue.

### Preview

[Link to Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cm-remove-edit-btn/)

### Solution

- Removed template page for the edit button 
- Removed both styles and js files that were associated with this button 
- Removed the forward in the global styles sheet 

### How To Test

1. Visit [preview link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cm-remove-edit-btn/) and ensure that button is no longer present 
2. Also visit [other preview link]() can scroll to the bottom and check that edit and last updated are no longer present. 
3. Check that footer link now reads `Submit issue on GitHub` and link takes user to issues page. 
4.  Check that any mention of the edit button is removed from the repo 

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

tagging supervisor for reference - @rayestrada

2024-01-30 18:01 UTC, mejiaj requested changes
Looks good for the most part. Found some old references in template we should remove to avoid any confusion.

- [x] References to css class `gh-edit-tools` are gone.
- [ ] References used in JS are gone.

I still see references to `data-gh-edit-page` in templates.

2024-01-30 21:04 UTC, nick-mon1 requested changes

2024-01-31 17:53 UTC, clmedders commented on themes/digital.gov/src/js/gh-edit-page.js
> -  const githubEditLinks = document.querySelectorAll("[data-gh-edit-page]");
updated and removed

2024-02-02 16:23 UTC, nick-mon1 submitted a review, later dismissed
What I Tested:

- [x] tested "Submit Github issue" link
- [x] removed `$path` when not used in templates/component

2024-02-02 16:26 UTC, nick-mon1 submitted a review, later dismissed
Approved

2024-02-05 15:03 UTC, nick-mon1 approved these changes

2024-02-08 18:36 UTC, mejiaj approved these changes
Approved.

I tested the following:
-  [x] References to `data-gh-edit-page` are gone.
-  [x] References to `gh-commit-info` are gone.
-  [x] No issues with buildJS task.
-  [x] No visual regressions.

2024-02-09 23:47 UTC, merged