Accessibility for teams content design page
GSA/digitalgov.gov pull request #7311
Opened 2024-02-12 19:53 UTC by nick-mon1

- First round of content edits
- Added note variant for voiceover, fixed headers

## Summary

Basic description of work done. Closes [#issue_no].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2024-02-12 20:14 UTC, nick-mon1 commented on content/guides/accessibility-for-teams/content-design.md
> +{{< /note >}}
Replaced list with `note variant="wcag"`variant.

<img width="1010" alt="Screen Shot 2024-02-12 at 2 44 49 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/3f1aeb02-bb78-422d-a087-9abe38dabc04">

2024-02-12 20:15 UTC, nick-mon1 commented on content/guides/accessibility-for-teams/content-design.md
>  {{< /ring >}}
TODO: We should modify the `ring` shortcode to take a header. Currently it displays a `h2` and breaks the guide structure.

2024-02-12 20:18 UTC, nick-mon1 commented on content/guides/accessibility-for-teams/content-design.md
>  {{< youtube XCa6U1BllCY >}}
Set `resources` from `h4` to `h3` to be more consistent with section content.

Replaced `youtube` link with hugo `youtube` shortcode which embeds in page.

2024-02-12 20:39 UTC, nick-mon1 commented on content/guides/accessibility-for-teams/content-design.md
> +{{< /note >}}
Replaced `accordion` to use `note` shortcode.

<img width="982" alt="Screen Shot 2024-02-12 at 2 44 59 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/b2c8bb67-4c69-445e-adef-68c08dea4253">


See [old voiceover accordion to compare](https://accessibility.digital.gov/content-design/information-architecture/#amendment-1).

2024-02-15 22:00 UTC, bonnieAcameron commented
@nick-mon1 I think the content page is long enough to warrant a navigation bar like we have on this HCD guide page: https://digital.gov/guides/hcd/discovery-concepts/.

2024-02-15 22:01 UTC, bonnieAcameron requested changes
Happy to discuss more about our approach at the P&I meeting next week

2024-02-23 18:34 UTC, nick-mon1 commented
Closed in favor of and moved these changes to https://github.com/GSA/digitalgov.gov/pull/7288.

2024-02-23 18:34 UTC, closed without merging