Fix glossary bug
GSA/digitalgov.gov pull request #7371
Opened 2024-03-01 15:47 UTC by nick-mon1

- Refactored template to hide header when summary box component is displayed
- Refactored conditional to check for nil
- Fixed logic to hide header

## Summary

Basic description of work done. Closes [#issue_no].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2024-03-01 16:12 UTC, nick-mon1 commented on themes/digital.gov/layouts/guides/single.html
> +      {{- end -}}
Check if `.Parent` page has `glossary` field set. This refers to the root `_index.md` in the guide directory.

2024-03-01 16:12 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/glossary.html
> +  <h2 class="dg-glossary__header">Glossary</h2>
Added class as a hook for the javascript.

2024-03-01 16:13 UTC, nick-mon1 commented on themes/digital.gov/src/js/summary-box.js
> +    "h2:not(.usa-summary-box__heading, .dg-guide__content-header-title, .dg-glossary__header)"
This query acts as "blacklist" of headers to not in the `summary box` component depending on the page it is called from.

2024-03-01 19:13 UTC, nick-mon1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [DG Bug - remove glossary H2 when not enabled on regular guide pages](https://trello.com/c/p74qol0k/825-dg-bug-remove-glossary-h2-when-not-enabled-on-regular-guide-pages)

2024-03-06 14:40 UTC, clmedders approved these changes
LGTM!

2024-03-07 14:16 UTC, mejiaj requested changes
Works well, nice job. Minor comments on adding documentation.

2024-03-07 14:16 UTC, mejiaj commented on themes/digital.gov/layouts/partials/core/glossary.html
Can we add a comment for this component?

It'd be nice to add what it is, where/how its used, and dependencies like `summary-box.js`.

2024-03-07 20:35 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/glossary.html
Yes, good call @mejiaj

2024-03-07 20:36 UTC, nick-mon1 commented on themes/digital.gov/src/js/summary-box.js
>    function createSummaryBox() {
JSDocs added 👍🏻

2024-03-14 18:22 UTC, mejiaj requested changes
Looks good overall. Added suggestions for clarity & code comments.

2024-03-15 19:19 UTC, nick-mon1 commented on themes/digital.gov/src/js/summary-box.js
> + */
Added a link to example page and markdown file and added more detail on how this component is implemented

2024-03-18 16:08 UTC, mejiaj approved these changes
LGTM, removed duplicate header in c993905b15.

2024-03-18 16:47 UTC, clmedders approved these changes

2024-03-26 19:39 UTC, merged