Replace gulp-responsive with sharp
GSA/digitalgov.gov pull request #7487
Opened 2024-04-08 18:35 UTC by nick-mon1

- [x] replaced gulp-responsive with sharp for image processing
- [x] reduced # of variants from 33 to 4
- [x] fixes image darkening bug with gulp-responsive

## Summary

Basic description of work done. Closes [#issue_no].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2024-04-10 17:06 UTC, clmedders commented
<img width="902" alt="Screenshot 2024-04-10 at 1 05 47 PM" src="https://github.com/GSA/digitalgov.gov/assets/88721460/5ce7e4c8-2875-47dd-892a-a747918ba37f">

@nick-mon1 im getting this error in my terminal when i run the `nps gulp upload` after i have added the test images...

2024-04-11 13:01 UTC, clmedders approved these changes

2024-04-11 16:08 UTC, mejiaj requested changes
@nick-mon1, in terminal could you run `npx eslint ./config/gulp/file-process.js` and fix the low LOE alerts? We can follow up on the rest in the next sprint.

2024-04-15 18:34 UTC, nick-mon1 commented
@mejiaj 

Refactored code to remove all errors. 
Running `npx eslint ./config/gulp/file-process.js` outputs:

```bash

/Users/nlyons/Documents/gsa/digitalgov.gov/config/gulp/file-process.js
   66:9   warning  Unexpected console statement  no-console
   84:11  warning  Unexpected console statement  no-console
  101:7   warning  Unexpected console statement  no-console
  115:7   warning  Unexpected console statement  no-console
  124:7   warning  Unexpected console statement  no-console
  133:3   warning  Unexpected console statement  no-console

✖ 6 problems (0 errors, 6 warnings)
```

2024-04-15 20:04 UTC, clmedders approved these changes
LGTM

I tested with the npx script and i am only get a warning but those console statments are used for debugging in the event of an error

2024-04-16 14:55 UTC, mejiaj reviewed
Code looks much better overall, thank you. Added some feedback based on a few test cases.

### 1. No images

Running `npx gulp upload` with an empty `content/upload/_inbox` directory I see the following message:

```bash
npx gulp upload
[09:26:23] Using gulpfile ~/web/digitalgov.gov/gulpfile.js
[09:26:23] Starting 'upload'...
[09:26:23] Starting 'fileTidy'...
[09:26:23] Finished 'fileTidy' after 376 μs
[09:26:23] Starting 'cleanInbox'...
(node:47441) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[09:26:23] Finished 'cleanInbox' after 4.49 ms
[09:26:23] Starting 'writeDataFile'...
[09:26:23] Finished 'writeDataFile' after 5.35 ms
[09:26:23] Starting 'processImages'...
[09:26:23] Finished 'processImages' after 199 μs
[09:26:23] Starting 'removeProcessedImage'...
Removing processed images
No images to process
Error processing file: [undefined]. ENOENT: no such file or directory, scandir './content/uploads/_working-images/to-process'
[09:26:23] Finished 'removeProcessedImage' after 1.09 ms
[09:26:23] Starting 'uploadImage'...
starting image upload
[09:26:23] Finished 'uploadImage' after 7.52 ms
[09:26:23] Starting 'uploadFile'...
starting file upload
[09:26:23] Finished 'uploadFile' after 1.15 ms
[09:26:23] Starting 'cleanup'...
[09:26:23] Finished 'cleanup' after 784 μs
[09:26:23] Finished 'upload' after 23 ms
```

This _looks_ to start three tasks: `upload, fileTidy, and cleanInbox`.  

We could improve clarity here by first checking the directory and **only** running the other tasks if there's a file.


```mermaid
graph TD;
    images_empty-->Yes;
    images_empty-->No;
    Yes-->Return;
    No-->processImages;
    processImages-->uploadImage;
    processImages-->writeDataFile;
    uploadImage-->cleanup;
```

Also curious, why do `uploadImage` and `uploadFile` run at the same time.

2024-04-16 14:55 UTC, mejiaj commented on config/gulp/file-process.js
> +}
## Optional

You could leverage [Path.parse()](https://nodejs.org/api/path.html#pathparsepath) here to use the native method for getting this information.

2024-04-16 21:04 UTC, nick-mon1 commented
@mejiaj 

These gulp `tasks` are all run with the `series` command, they will run no matter the condition of the previous task. The [API docs](https://gulpjs.com/docs/en/api/concepts) do not provide a way to exit a task on a condition gracefully. We could throw an error but this will cause build errors with **circleci**:

```javascript
process.exit();
```

This produces:

```bash
[16:37:40] Using gulpfile ~/Documents/gsa/digitalgov.gov/gulpfile.js
[16:37:40] Starting 'upload'...
[16:37:40] Starting 'fileTidy'...
[16:37:40] Finished 'fileTidy' after 663 μs
[16:37:40] Starting 'cleanInbox'...
(node:30491) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[16:37:40] Finished 'cleanInbox' after 9.22 ms
[16:37:40] Starting 'writeDataFile'...
[16:37:40] Finished 'writeDataFile' after 11 ms
[16:37:40] Starting 'processImages'...
[16:37:40] Finished 'processImages' after 311 μs
[16:37:40] Starting 'removeProcessedImage'...
Removing processed images
No images to process
[16:37:40] The following tasks did not complete: upload, <series>, removeProcessedImage
[16:37:40] Did you forget to signal async completion?
```

We would need to refactor these tasks across 3 files to add better job control and error handling, which looks like limited for our needs based on the `gulp` API.

An alternative would be to remove the reliance on `gulp` and use **es modules** to handoff each of these functions (prep, process, upload) that would allow us to have more control of the process.

2024-04-17 13:39 UTC, clmedders commented
is it smart to get rid of gulp?  since USWDS uses it or maybe since this is outside of that package then we might be ok?  I see what James is saying and I thought that we would always have some kind of image there so it wouldn't be an issue.  Just some thoughts...

2024-04-18 13:25 UTC, mejiaj approved these changes
Approving because this issue is to fix image processing & composition is expanding scope.

You can use conditionals and have quite a bit of freedom composing tasks. See GulpJS docs on [composing tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks/#compose-tasks).

2024-04-18 20:13 UTC, clmedders approved these changes

2024-04-24 20:11 UTC, merged