Solves 7528
GSA/digitalgov.gov pull request #7538
Opened 2024-04-30 17:55 UTC by RileySeaburg

## Summary

Basic description of work done. Closes [#issue_no].

### Preview

[Link to Preview]()

### Solution

### How To Test

1. First Step
2. Second Step
3. Third Step

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2024-04-30 20:04 UTC, nick-mon1 requested changes

2024-04-30 20:04 UTC, nick-mon1 commented on content/news/2013/02/2013-02-14-qr-codes.md
> +<!-- TODO: this video does not exist -->
Let's remove this comment.

2024-04-30 20:04 UTC, nick-mon1 commented on content/news/2016/03/2016-03-08-quizzes-the-secret-weapon-of-the-worlds-best-content-creators.md
> +
We can remove this and use the archive warning banner instead.

2024-04-30 20:04 UTC, nick-mon1 commented on content/news/2016/03/2016-03-08-quizzes-the-secret-weapon-of-the-worlds-best-content-creators.md
> +To learn more about quizzes, you can view the entire webinar.
Let's remove this.

2024-04-30 20:04 UTC, nick-mon1 commented on content/news/2016/07/2016-07-14-analytics-trainings-2016-so-far.md
> +
We can remove this and use the archive warning banner instead.

2024-04-30 20:04 UTC, nick-mon1 commented on content/news/2017/09/2017-09-20-a-conversation-with-itif-about-state-federal-government-websites.md
> +
We can remove this and use the archive warning banner instead.

2024-04-30 20:04 UTC, nick-mon1 commented on content/resources/digitalgov-user-experience-program-speaking-opportunities.md
> +
We can remove this and use the archive warning banner instead.

2024-04-30 20:57 UTC, RileySeaburg commented
@nick-mon1  I think I addressed you requests but Idk if I checked all the boxes to say I did.

2024-04-30 21:05 UTC, nick-mon1 commented
@RileySeaburg We should have a link to each preview page to make testing easier. I've tested locally and everything looks good.

2024-04-30 21:10 UTC, nick-mon1 requested changes

2024-04-30 21:10 UTC, nick-mon1 commented on package-lock.json
We should exclude these changes, we update packages for security/maintenance in separate PR's.

2024-05-01 13:07 UTC, nick-mon1 approved these changes

2024-05-02 20:43 UTC, RileySeaburg commented
Solves #7538

2024-05-16 14:48 UTC, ToniBonittoGSA commented on content/news/2016/03/2016-03-08-quizzes-the-secret-weapon-of-the-worlds-best-content-creators.md
Hi @RileySeaburg 

Original:

> `[Quizzes: The Secret Weapon of the World’s Best Content Creators](https://www.youtube.com/watch?v=0q4ueTABYnQ),`

was changed to 

> `[This link no longer exists](https://www.youtube.com/watch?v=0q4ueTABYnQ),`

The copy "This link no longer exists" removes context, doesn't tell user **what** no longer exists. Also, we wouldn't link to something that no longer exists. Pls use:

> `Quizzes: The Secret Weapon of the World’s Best Content Creators,`

2024-05-16 14:53 UTC, ToniBonittoGSA commented on content/news/2016/05/2016-05-12-using-pirate-metrics-to-analyze-your-mobile-applications-audience.md
@RileySeaburg 
The banner alerts users that content is older and links may no longer work. 
Remove the link, but keep the copy. Restore: 

> Watch the webinar to see how you can learn how to use pirate metrics in your agency!

2024-05-16 14:55 UTC, ToniBonittoGSA commented on content/news/2016/07/2016-07-14-analytics-trainings-2016-so-far.md
@RileySeaburg 

Like the others; pls restore the "## DAP 101 Training" section; just remove the links.

2024-05-16 14:57 UTC, ToniBonittoGSA commented on content/resources/digitalgov-user-experience-program-speaking-opportunities.md
@RileySeaburg 

Like the others; restore "## Our Recorded Webinars" section, just remove the vids

2024-05-16 15:00 UTC, ToniBonittoGSA commented on content/resources/inventory-data-gov-guide.md
@RileySeaburg 

For 
> Data.gov, working with DigitalGov University, presented a webinar for agencies interested in using inventory on December 16, 2014\. For more information, consult the recording of the [This link is no longer maintained](http://youtu.be/ciLYjDsF4lo).

Use

> Data.gov, working with DigitalGov University, presented a webinar for agencies interested in using inventory on December 16, 2014. For more information, consult the recording of the webinar.

(also removes odd backslash at end of the first sentence)

Thx!

2024-05-16 19:44 UTC, ToniBonittoGSA approved these changes

2024-05-16 19:59 UTC, merged