Create Event “2024/05/2024-05-02-uswds-monthly-call-may-2024”
GSA/digitalgov.gov pull request #7541
Opened 2024-05-02 15:51 UTC by brunerae

Automatically generated by Decap CMS

[Preview of event page](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cms/events/2024/05/2024-05-02-uswds-monthly-call-may-2024/event/2024/05/16/uswds-monthly-call-may-2024/)

2024-05-02 17:36 UTC, nick-mon1 approved these changes
Just add a minor touch to the hyphens for the speakers.

<img width="642" alt="Screenshot 2024-05-02 at 1 30 42 PM" src="https://github.com/GSA/digitalgov.gov/assets/104778659/ee34f391-4c52-4bd6-ac22-9eac4d2e0849">

2024-05-03 19:11 UTC, mejiaj commented
@nick-mon1 good note. 

Can we make those hyphens consistent? Some are bold and others aren't.

2024-05-03 19:12 UTC, mejiaj requested changes

2024-05-03 19:12 UTC, mejiaj commented on content/events/2024/05/2024-05-02-uswds-monthly-call-may-2024.md
> +* **Whitney Quesenbery** - Co-founder, Center for Civic Design
For consistency, looks like hyphen needs to be updated.

```suggestion
* **Whitney Quesenbery** **-** Co-founder, Center for Civic Design
```

2024-05-23 17:09 UTC, closed without merging