Hotfix/rs convert jpg png
GSA/digitalgov.gov pull request #7686
Opened 2024-06-14 19:42 UTC by RileySeaburg

## Summary 

This hotfix addresses an issue where uploading JPG/JPEG images was causing errors and broken images on the website. The fix converts JPG/JPEG images to PNG format before further processing. Closes #7685.

### Preview

N/A

### Solution

- Added a new async function `convertJpgToPng` in `file-prep.js` to convert JPG/JPEG images to PNG format using the sharp library. 
- Modified the `fileTidy` function to call `convertJpgToPng` when a JPG/JPEG file is encountered. The original JPG file is deleted after conversion.
- Added error handling to log any errors that occur during the JPG to PNG conversion.
- Created a new `readme.md` file to provide an overview of the image and file upload processing functionality, usage instructions, configuration details, and dependencies.

### How To Test

1. Upload a JPG/JPEG image to the `content/uploads/_inbox` directory.
2. Run the `npx gulpupload` command.
3. Verify that the JPG/JPEG image is converted to PNG format in the `content/uploads/_working-images/to-process` directory.
4. Check the Images feed and Facebook Debugger to ensure the converted PNG image is displayed correctly without any errors.

---

### Dev Checklist

- [x] PR has correct labels 
- [x] A11y testing (voice over testing, meets WCAG, run axe tools)
- [x] Code is formatted properly

2024-06-14 19:42 UTC, RileySeaburg commented
I need to clean up some delete folder errors, but the hotfix is working.

2024-06-17 13:40 UTC, mejiaj submitted a review, later dismissed
> [!NOTE]  
> I only testing uploading JPG & PNG.

I was able to successfully test uploading a JPG & PNG file. The JPG was successfully converted and the PNG uploaded as-is.

---

I hope we continue to look for a workaround for JPGs or a leaner alternative. PNGs are heavier and worse quality in comparison.

2024-06-17 13:40 UTC, mejiaj commented on config/gulp/readme.md
> +2. Run the `npm run gulpupload` command to execute the entire upload process, including file preparation, image processing, and uploading to Amazon S3.
Missing space in command name.

```suggestion
2. Run the `npm run gulp upload` command to execute the entire upload process, including file preparation, image processing, and uploading to Amazon S3.
```

2024-06-17 13:40 UTC, mejiaj commented on config/gulp/readme.md
> +The `gulpupload` command will perform the following steps:
```suggestion
The `gulp upload` command will perform the following steps:
```

2024-06-17 14:05 UTC, RileySeaburg commented
> Note
> 
> I only testing uploading JPG & PNG.
> 
> I was able to successfully test uploading a JPG & PNG file. The JPG was successfully converted and the PNG uploaded as-is.
> 
> I hope we continue to look for a workaround for JPGs or a leaner alternative. PNGs are heavier and worse quality in comparison.

As per @nick-mon1 the action plan was to 

- [x] Add a hotfix to the image upload process 
- [ ] Determine if webp is a viable alternative.
- [ ] Replace jpg-> png code with jpg -> webp code.

Does this sound like a plan?

2024-06-17 15:08 UTC, RileySeaburg commented
> @RileySeaburg it'd be nice to find a solution to the JPG issue either way. But I don't want to slow us down from higher priority items.
> 
> One last note, can we please remove any test images from the S3 bucket?

Done

2024-06-18 14:02 UTC, nick-mon1 requested changes
What I tested:

- jpg to png
- png
- static file (pptx)

Static file uploading works but the output has changed. Just making a note of the differences.


**Before**

```bash
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[14:42:16] Finished 'cleanInbox' after 12 ms
[14:42:16] Starting 'writeDataFile'...
[14:42:16] Finished 'writeDataFile' after 18 ms
[14:42:16] Starting 'variants'...
[14:42:16] Starting 'removeProcessedImage'...
Removing processed images
[14:42:16] Finished 'variants' after 6.6 ms
[14:42:16] Finished 'removeProcessedImage' after 6.9 ms
[14:42:16] Starting 'uploadImage'...
starting image upload
[14:42:16] Finished 'uploadImage' after 12 ms
[14:42:16] Starting 'uploadFile'...
starting file upload
file is written
[14:42:16] Uploading .....  uswds-monthly-call-april-2024.pptx
[14:42:16] Uploaded! .....  uswds-monthly-call-april-2024.pptx
[14:42:16] Finished 'uploadFile' after 341 ms
[14:42:16] Starting 'cleanup'...
[14:42:16] Finished 'cleanup' after 4.5 ms
[14:42:16] Finished 'upload' after 400 ms
```

**After**

```bash
[09:27:57] Using gulpfile ~/Documents/gsa/digitalgov.gov/gulpfile.js
[09:27:57] Starting 'upload'...
[09:27:57] Starting 'fileTidy'...
Moving file from content/uploads/_inbox/s3-test-uswds-monthly-call-may-2024.pptx to content/uploads/_working-files/to-process/s3-test-uswds-monthly-call-may-2024.pptx
[09:27:57] Finished 'fileTidy' after 2.58 ms
[09:27:57] Starting 'cleanInbox'...
[09:27:57] Finished 'cleanInbox' after 8.86 ms
[09:27:57] Starting 'writeDataFile'...
[09:27:57] Finished 'writeDataFile' after 29 ms
[09:27:57] Starting 'processImages'...
[09:27:57] Finished 'processImages' after 308 μs
[09:27:57] Starting 'removeProcessedImage'...
Removing processed images
No images to process
Error processing file: [undefined]. ENOENT: no such file or directory, scandir './content/uploads/_working-images/to-process'
[09:27:57] Finished 'removeProcessedImage' after 2.19 ms
[09:27:57] Starting 'uploadImage'...
[09:27:57] Finished 'uploadImage' after 12 ms
[09:27:57] Starting 'uploadFile'...
file is written
(node:6841) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[09:28:09] [create] static/s3-test-uswds-monthly-call-may-2024.pptx
[09:28:09] Finished 'uploadFile' after 12 s
[09:28:09] Starting 'cleanup'...
cleanup
[09:28:09] Finished 'cleanup' after 5.93 ms
[09:28:09] Finished 'upload' after 12 s
```

2024-06-18 14:36 UTC, RileySeaburg commented on config/gulp/readme.md
> +2. Run the `npm run gulp upload` command to execute the entire upload process, including file preparation, image processing, and uploading to Amazon S3.
Should add the script to package.json

2024-06-18 14:43 UTC, RileySeaburg commented on config/gulp/file-prep.js
> +         let result =  await convertJpgToPng(path.join(paths.uploads, file)).catch
All set

2024-06-18 14:43 UTC, RileySeaburg commented
All set on this

2024-06-18 14:47 UTC, nick-mon1 approved these changes

2024-06-25 15:28 UTC, mejiaj submitted a review, later dismissed

2024-06-26 17:06 UTC, RileySeaburg commented
New logs associated with this PR

![image](https://github.com/GSA/digitalgov.gov/assets/48305658/e9e01917-ffdb-4ee6-8a38-d27836bfda3d)

2024-07-02 20:06 UTC, RileySeaburg commented
Closed merged into #7671

2024-07-02 20:06 UTC, closed without merging