Community Sidebar Events Links
GSA/digitalgov.gov pull request #7748
Opened 2024-06-28 18:17 UTC by lcummings12

## Summary

Implemented a new partial, `primary_communities.html ` to display the core COPs on any events page. [#issue_no]. Set the partial to display on community pages in the side bar. 

### Preview

[Link to Preview]()

### Solution
The `primary_communities `  partial filters and displays communities where the `dg_highlight ` is set to true, signifying a "core" community. This partial is styled identity to the `get_related` partial that this replaces. 
### How To Test
Proposed Change
<img width="1440" alt="Screen Shot 2024-06-28 at 1 13 57 PM" src="https://github.com/GSA/digitalgov.gov/assets/172419749/aa5b94db-a985-4702-bcaf-2a1f722e4c59">

Production 
<img width="1440" alt="Screen Shot 2024-06-28 at 1 14 43 PM" src="https://github.com/GSA/digitalgov.gov/assets/172419749/93d57008-e386-4808-8f7d-f3e93de87639">

1. Start a local server.
2. Open any Event page 
3. Assure the only difference between the production site and local site is the core COP sidebar

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

2024-07-01 20:42 UTC, nick-mon1 requested changes

2024-07-01 20:42 UTC, nick-mon1 commented on themes/digital.gov/layouts/events/single.html
> +
This should come after the authors section. See live site — https://digital.gov/event/2022/05/17/how-to-build-your-digital-dream-team/

2024-07-01 20:42 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/primary_communities.html
> +{{ $mainCommunities = union $featuredCommunity $mainCommunities }}
Add comments at top of page explaining what this partial does. Comments will help explain the what and why for the code.

2024-07-01 20:42 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/primary_communities.html
Try renaming to `display_primary_communities.html` to be more descriptive.

2024-07-03 14:13 UTC, mejiaj reviewed
Thanks for helping us improve these components. Added a few comments below.

2024-07-03 14:13 UTC, mejiaj commented on themes/digital.gov/layouts/partials/core/primary_communities.html
### Question

Where is this used? Unsure how this fits in with the previous communities in `get_related.html`.

https://github.com/GSA/digitalgov.gov/blob/a343de8cc9401a6e201a322f0349f3d82b1bcfba/themes/digital.gov/layouts/partials/core/get_related.html#L22-L59

2024-07-03 15:57 UTC, lcummings12 commented on themes/digital.gov/layouts/partials/core/primary_communities.html
This was the part of the side bar that was present prior to these changes. At least in the events section, it is currently unused

2024-07-08 14:19 UTC, mejiaj commented on themes/digital.gov/layouts/partials/core/primary_communities.html
Okay, thanks. We can look into whether it's worth combining or keeping separate in future work.

2024-07-11 18:12 UTC, nick-mon1 approved these changes
Looks good, just have a question about removing the duplicate partial.

2024-07-11 18:12 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/primary_communities.html
### Question

Should we remove this file? Looks to be same code as `primary-communities.html` minus the comments at the top.

2024-07-11 19:50 UTC, lcummings12 commented on themes/digital.gov/layouts/partials/core/primary_communities.html
Oh yeah that carried over from my other branch. ill remove it now.

2024-07-11 20:21 UTC, nick-mon1 approved these changes

2024-07-12 13:34 UTC, mejiaj approved these changes
My comments have been resolved and visually looks good. I tested this [preview link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/Update-Community-Links-Events/event/2024/06/20/uswds-monthly-call-june-2024/).

---

@lcummings12 for future PR's can you add the Cloud Pages preview link in your PR description?

It gets added on every PR:
![image](https://github.com/user-attachments/assets/cb0f5428-7492-48d0-a32b-b4e152586c1a)

2024-07-16 12:48 UTC, RileySeaburg approved these changes
Great job addressing all the feedback. 

Thank you for helping us to improve this important component!

2024-07-16 13:02 UTC, merged