Refactor card-quote
GSA/digitalgov.gov pull request #7823
Opened 2024-07-29 21:15 UTC by lcummings12

## Summary

Refactored the card-quote.html shortcode to include the blockquote component classes and align its structure more closely with the note.html style.

## Preview

[Link to Preview]()

## Solution

The solution involved refactoring the card-quote.html shortcode to improve its structure and ensure the blockquote element has appropriate component classes.
Extracted bg, cite, and text as variables at the beginning.
Added card-quote__blockquote class to the blockquote element.
Ensured the logic and structure align more closely with the note.html style.

## How To Test
The changes made were solely refactoring. If properly implemented, there should no visual change. 
| Proposed change                                                                                  | Production                                                                                       |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------ |
| [Proposed change](http://localhost:1313/2024/07/08/a-small-teams-journey-through-digital-maturity/) | [Production](https://digital.gov//2024/07/08/a-small-teams-journey-through-digital-maturity/) |

2024-07-31 17:33 UTC, nick-mon1 commented
@lcummings12 This improvement is great, don't forget to update the `_card-quote.scss` with the new class names.

2024-08-02 19:35 UTC, lcummings12 commented
@nick-mon1  Ended up removing that class as it served no purpose other than being consistent with the model file.

2024-08-06 14:48 UTC, nick-mon1 requested changes

2024-08-06 14:48 UTC, nick-mon1 commented on themes/digital.gov/layouts/shortcodes/card-quote.html
> +*/}}
### Improvement

Added comments to explain the component.

2024-08-06 14:48 UTC, nick-mon1 commented on themes/digital.gov/layouts/shortcodes/card-quote.html
### Suggestion

This component lives in the short code directory, we could move this to partials and refactor this file to use the partial.

Why? This will keep our files more organized and consistent.

2024-08-06 14:48 UTC, nick-mon1 commented on themes/digital.gov/layouts/shortcodes/card-quote.html
> +      <span class="card_quote__quotation-mark">“</span>
### Improvement

I've renamed `q` to prefer BEM naming convention and for clarity.

2024-08-06 14:48 UTC, nick-mon1 commented on themes/digital.gov/layouts/shortcodes/card-quote.html
> +  <div class="card-quote {{ if $bg }}card-quote--{{ $bg }}{{ end }}">
### Improvement

This uses the BEM naming convention for variants.

2024-08-07 19:47 UTC, lcummings12 commented
@nick-mon1 Improved the implementation as you suggested by restructuring into a shortcode / partial setup where the `quote-block.html` partial calls the `quote-block.html` shortcode. Additionally, renamed and reformatted `card-quote.js` to support the new setup with `quote-block`.  Switched out all instances of the original shortcode in the .md files with the updated version.  For testing purpose, I created regression file with the variants I could think of. I attached it to the PR, but here is an image of it.
<img width="552" alt="image" src="https://github.com/user-attachments/assets/0043e2c4-5fb4-4abf-a12f-a8eff8dc29c1">

2024-08-08 15:31 UTC, RileySeaburg submitted a review, later dismissed
Great attention to detail on this.

2024-08-08 16:11 UTC, nick-mon1 approved these changes
Thanks @lcummings12 for these updates. I fixed a couple of the styles to match font styles, all set.

2024-08-08 16:54 UTC, merged