Add CoP membership to usa-cards
GSA/digitalgov.gov pull request #7836
Opened 2024-07-31 15:43 UTC by ch-tyson

## Summary

Basic description of work done.

## Preview

[Link to Preview]()

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

2024-07-31 16:01 UTC, ToniBonittoGSA commented
Hi @ch-tyson 

[Homepage preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/tc-CoP-membership/) - looks good

[Communities page preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/tc-CoP-membership/) - alignment is off

2024-07-31 17:30 UTC, nick-mon1 commented
@ch-tyson Due to some testing by @RileySeaburg there are two un-needed `yaml` files in your PR, please remove.

2024-08-02 16:11 UTC, nick-mon1 requested changes
Overall, this looks good @ch-tyson.
Added some minor suggestions and improvements.

### What I Tested

- a11y
- responsive layout
- code styles and markup

2024-08-02 21:44 UTC, ch-tyson commented on themes/digital.gov/src/scss/new/home/_communities.scss
Went ahead and deleted it!

2024-08-03 00:44 UTC, merged