Fixed svg artwork clipping paths
GSA/digitalgov.gov pull request #7923
Opened 2024-09-06 14:23 UTC by nick-mon1

## Summary
Fixed clipping path layers in the svg to show full circle path.

## Preview

[Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-update-community-svgs/communities/)

<details><summary>Screen Shots</summary>
<p>

Before
<img width="1487" alt="Screenshot 2024-09-09 at 1 41 32 PM" src="https://github.com/user-attachments/assets/a364b08c-6534-47ae-b219-e7eb640651c9">

After
<img width="1502" alt="Screenshot 2024-09-09 at 1 42 43 PM" src="https://github.com/user-attachments/assets/2fc06b6d-ed8d-4887-9131-697e59151af3">

</p>
</details> 

## Suggestion

@makaylahipke I noticed some minor tweaks we could make in the `svg` artwork.

Notice how the teal and purple icons outlines fill the whole circle and could centered and scaled down a bit to fit within the circle, it looks more balanced with the other icons.

What do you think?

<img width="383" alt="Screenshot 2024-09-06 at 10 26 33 AM" src="https://github.com/user-attachments/assets/a46cd6e5-ec07-4f1e-95f8-b38eb7e98e10">

<img width="185" alt="Screenshot 2024-09-06 at 10 30 40 AM" src="https://github.com/user-attachments/assets/f5b377e8-1933-4fb2-a6dd-6b24e03eb3b5">

2024-09-09 13:51 UTC, makaylahipke commented
@nick-mon1 **Yes!** This is a huge improvement and a breath of fresh air to those icon designs. I had only noticed this issue with web analytics and web managers, so glad you caught the other two as well. Let's proceed with these--thank you thank you.

2024-09-09 18:52 UTC, makaylahipke requested changes
Requested a tweak to one of the icons (social media)

2024-09-09 18:52 UTC, makaylahipke commented on themes/digital.gov/static/img/communities-social-media.svg
I keep looking at this one--I think because it's so asymmetrical, it keeps feeling like it's too far right. Would it be possible to reduce the scale of the artwork just a little? Perhaps closer in WxH to the UX artwork?

2024-09-10 20:49 UTC, nick-mon1 commented on themes/digital.gov/static/img/communities-social-media.svg
Yes and yes! How does it look to your eye now?

2024-09-10 20:58 UTC, makaylahipke commented on themes/digital.gov/static/img/communities-social-media.svg
@nick-mon1 MUCH better. Thank you!

Also, I think the same issue happened on this Contact Center icon that I had a few times. I don't know why, but Illustrated messes up in the paths and makes the edges choppy. 
![contact_center](https://github.com/user-attachments/assets/f55050fd-d6e1-448c-86bd-a299d844e929)

2024-09-10 21:01 UTC, nick-mon1 commented on themes/digital.gov/static/img/communities-social-media.svg
@makaylahipke I noticed that but didn't it in my preview, probably due to some caching issues. Will get this corrected ✅

2024-09-11 13:33 UTC, nick-mon1 commented on themes/digital.gov/static/img/communities-social-media.svg
Fixed with 5e1b29ac40ab6463353ecb6920a1d15b03533cc5

2024-09-11 16:48 UTC, merged