Create Image upload “content-uploads-_inbox-warning-banner-jpg”
GSA/digitalgov.gov pull request #7942
Opened 2024-09-13 17:36 UTC by nick-mon1

Automatically generated by Decap CMS

2024-09-13 19:57 UTC, bonnieAcameron requested changes
Looks good, but the image needs alt-text. Suggested some for you to review/commit.

2024-09-13 19:57 UTC, bonnieAcameron commented on data/images/warning-banner.yml
> +  alt      :
```suggestion
  alt      :  A screenshot of a now-defunct warning banner that GSA once used to tell users that the program they were opening was for official use only. There are dozens of asterisks and much of the text is in all-caps, creating an alarming experience what was an every-day message."
```

2024-09-17 14:14 UTC, clmedders commented
@bonnieAcameron thank you for adding that!

@RileySeaburg this is ready for a final review and merge

2024-09-18 12:57 UTC, RileySeaburg approved these changes
Awesome job, merging because the suggested changes have been addressed.

2024-09-18 12:58 UTC, RileySeaburg commented
I can't merge actually until you approve @bonnieAcameron

2024-09-26 18:19 UTC, bonnieAcameron approved these changes

2024-10-04 19:41 UTC, closed without merging