Cltm archive uswdsblogs 2
GSA/digitalgov.gov pull request #8022
Opened 2024-10-10 17:17 UTC by camillemorrow

## Summary

Archived 4 pages and added redirects to corresponding topic pages.

## Preview

[Link to "3 teams..."](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cltm-archive-uswdsblogs-2/2016/04/06/three-teams-using-the-draft-u-s-web-design-standards-talk-about-their-experiences/)

[link to "making the draft..."](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cltm-archive-uswdsblogs-2/2016/03/16/making-the-draft-u-s-web-design-standards-better-through-your-feedback/)

[link to "how to integrate the draft..."](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cltm-archive-uswdsblogs-2/2016/03/25/how-to-integrate-the-draft-u-s-web-design-standards-into-existing-projects/)

[link to "fractal..."](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cltm-archive-uswdsblogs-2/2017/06/13/fractal-and-federalist-join-the-u-s-web-design-standards/)

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. Check that all original pages are archived and instead redirect.
2.  Make sure each the correct pages redirect to either the Design topic page or the Open Source topic page:

- https://digital.gov/2016/04/06/three-teams-using-the-draft-u-s-web-design-standards-talk-about-their-experiences/
- https://digital.gov/2016/03/16/making-the-draft-u-s-web-design-standards-better-through-your-feedback/
- https://digital.gov/2016/03/25/how-to-integrate-the-draft-u-s-web-design-standards-into-existing-projects/
- should redirect to: https://digital.gov/topics/design/
- 
- https://digital.gov/2017/06/13/fractal-and-federalist-join-the-u-s-web-design-standards/
- should redirect to: https://digital.gov/topics/open-source/

2024-10-11 17:39 UTC, bonnieAcameron requested changes
Requested changes: please update the file that the archived pages will redirect to. This entails:

1. Remove the "redirectto" additions from the metadata/frontmatter of the archived pieces
2. Add the alias (unique URL/string) of the archived piece to the page that it will redirect to (Further examples of this are in the documentation).

Let me know if you have questions!

2024-10-11 19:51 UTC, bonnieAcameron approved these changes

2024-10-11 22:45 UTC, ToniBonittoGSA commented
@camillemorrow Pls add the topics back in for the 4 blog pages, thx!

2024-10-17 15:16 UTC, bonnieAcameron approved these changes

2024-10-17 21:04 UTC, merged