Fix community upcoming events
GSA/digitalgov.gov pull request #8075
Opened 2024-10-17 18:10 UTC by nick-mon1

- **Updated template to display up-coming events**
- **Removed old front matter field, use event_cop instead**

## Summary

Basic description of work done.

## Preview

[Link to Preview]()

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

2024-10-22 19:22 UTC, RileySeaburg requested changes
@nick-mon1 

I get an error when testing this
[Logs](https://pages.cloud.gov/sites/193/builds/399210/logs)
```

2024-10-22 19:06:47 INFO [build-hugo] hugo version: $(/tmp/work/hugo version)

2024-10-22 19:06:47 INFO [build-hugo] Building site with hugo

2024-10-22 19:06:47 INFO [build-hugo] Start building sites …

2024-10-22 19:06:47 INFO [build-hugo] hugo v0.133.1-47d00202e7e61769ce4d14691e43b27852c9cce4 linux/amd64 BuildDate=2024-08-26T13:58:46Z VendorInfo=gohugoio

2024-10-22 19:06:58 INFO [build-hugo] Total in 11496 ms

2024-10-22 19:06:58 INFO [build-hugo] Error: error building site: render: failed to render pages: render of "page" failed: "/tmp/work/site_repo/themes/digital.gov/layouts/communities/single.html:61:18": execute of template failed: template: communities/single.html:61:18: executing "content" at <partial "core/get-upcomingevents.html" .>: error calling partial: "/tmp/work/site_repo/themes/digital.gov/layouts/partials/core/get-upcomingevents.html:14:15": execute of template failed: template: partials/core/get-upcomingevents.html:14:15: executing "partials/core/get-upcomingevents.html" at <strings.Contains>: error calling Contains: unable to cast []string{"communicators"} of type []string to string

2024-10-22 19:06:58 ERROR [main] There was a problem running Hugo, see the above logs for details.
```

2024-10-22 21:05 UTC, nick-mon1 commented
@RileySeaburg Fixed the previous merge conflicts that were causing the build error.

2024-10-23 21:10 UTC, RileySeaburg approved these changes
Cool this works for me.

![image](https://github.com/user-attachments/assets/3bcb89b2-2122-4744-a242-67a0812aa00e)


@ToniBonittoGSA  I'll let you do the content audit and merge if you feel it's ready.

2024-10-23 21:37 UTC, ToniBonittoGSA approved these changes

2024-10-23 21:37 UTC, merged