Remove unused events and join templates
GSA/digitalgov.gov pull request #8174
Opened 2024-11-06 20:26 UTC by nick-mon1

- **Merge branch 'main' into nl-update-community-upcoming-events**
- **Removed unused event and join form templates**

## Summary

Basic description of work done.

## Preview

[Link to Preview]()

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

2024-11-07 15:06 UTC, RileySeaburg commented
@ToniBonittoGSA, I'll let you approve & merge this

2024-11-07 15:20 UTC, ToniBonittoGSA commented
> @ToniBonittoGSA, I'll let you approve & merge this

I left a noite in JIRA, @RileySeaburg

2024-11-07 21:52 UTC, nick-mon1 commented
@ToniBonittoGSA @RileySeaburg 
This PR is just for removing un-used templates. #8138 addresses the last mod date.

2024-11-07 22:09 UTC, RileySeaburg requested changes

2024-11-07 22:09 UTC, RileySeaburg commented on themes/digital.gov/layouts/partials/core/last-updated.html
@nick-mon1 this introduces an additional file no?

I believe this is what we want removed first.

2024-11-08 14:21 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/core/last-updated.html
Ahhh, this should not be here. Thanks

2024-11-08 16:09 UTC, closed without merging