Remove author landing page and metadata
GSA/digitalgov.gov pull request #8216
Opened 2024-11-26 19:41 UTC by nick-mon1

## Summary

Basic description of work done.

## Preview

[Link to Preview]()

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

2024-12-09 14:33 UTC, camillemorrow submitted a review, later dismissed

2024-12-13 21:34 UTC, bonnieAcameron requested changes
There are some bits and pieces of metadata or helper text that I've flagged for removal. Although I have only flagged them in 1-2 places, they actually appear throughout the 2 sub-PRs. Some metadata still contains PII. 

I also have a question about the consistency of the agency field, whether it is acronym only or spelled out (I suggest the latter, but I want to make sure that it is a proactive decision)

2025-03-05 14:22 UTC, ToniBonittoGSA submitted a review, later dismissed

2025-03-05 19:19 UTC, ToniBonittoGSA approved these changes

2025-03-05 19:20 UTC, merged