Create JSON endpoints needed for migration source in Hugo
GSA/digitalgov.gov pull request #8254
Opened 2024-12-17 15:23 UTC by nick-mon1

- **First steps for json endpoints**
- **Reviewed all json endpoints**
- **Refactored endpoints, authors and events are done**
- **Consolidated to README.md**
- **5 content types setup**

## Summary

Basic description of work done.

## Preview

[Link to Preview]()

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

2025-01-28 15:02 UTC, mattsqd commented
@nick-mon1 I merged my branch (https://github.com/GSA/digitalgov.gov/pull/7840/files) that updates the endpoint for images into this one so we have all the migration stuff in one branch.
I also:
* added uid field to all endpoints that is slug and if that's empty, defaults to .Name if slug is empty, just in case.
* Used relative link instead of permanent link for every endpoints URL field.
* Changed aliases endpoint to redirects, since that is how they are treated in Drupal.

This is looking great, I can't wait to start testing this against actually Drupal migrations. I'm not going to merge this and instead just leave this as a long living branch as we update it with subsequent tasks.

2025-02-05 14:21 UTC, mattsqd commented
I'm getting a JSON parse error on [topics](http://localhost:1313/topics/v1/json/).
I think if we `| jsonify` all the values it won't happen. For example, it's [field_summary ](https://github.com/GSA/digitalgov.gov/blob/743ede775543576d50886bb39b5100008fbdd966/themes/digital.gov/layouts/partials/api/metadata.html#L11)that is causing topics to not be valid

2025-02-05 16:09 UTC, mattsqd commented
Where is the CSV that you mentioned for the redirects? I also am not sure where the code is you used to generate it (I might be blind).
`default/list.json.json` Seems to just return all top level pages. Do we have an end point for 'Basic Pages' yet? For us, that would be everything in the `content/about` directory. The other thing we'll need, is an endpoint for `data/files`, which should be pretty easy since it's nearly identical to the images endpoint.

2025-02-05 16:09 UTC, mattsqd requested changes
The endpoints are coming alive! I just had a few points and questions in some comments.

2025-02-11 19:03 UTC, mattsqd commented
For the authors endpoint:
* abigail-abby-bowman does not have a field_display_name
* For some reason, the author landing page is the first item in the endpoint

2025-02-12 21:16 UTC, nick-mon1 commented on themes/digital.gov/layouts/partials/api/topics-metadata.html
> +    "field_featured_resource": "{{ .link }}",
See https://github.com/GSA/digitalgov.gov/blob/4c5e3df9aabddbfdda976fa0dc421149daeda0ff/endpoint-scripts/mocks/topics-mock.json.

2025-02-14 18:43 UTC, nick-mon1 commented
@mattsqd I've added the `field_body` to all content types. It works for all content types except news, there is a break somewhere possibly related to markdown formatting, shortcodes parsing or an improperly formatted file.

I noticed that for events ([link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-json-endpoints/events/index.json)) there are newlines within html tags. I think this is related to the markdown parsing some shortcodes.

Good news is that once we merge https://github.com/GSA/digitalgov.gov/pull/8320 it should make it easier to address issues. We are shooting for mid to late next week to get that ready.

2025-02-27 19:47 UTC, mattsqd commented
@nick-mon1 we have a topic and a community that are trying to be the source of the same redirect
![image](https://github.com/user-attachments/assets/1430f470-f6b4-4a22-b8ff-c6cdbf6189aa)
Can we remove the alias from one, please?

2025-08-04 07:08 UTC, closed without merging